### ISSUE TITLE
AutoDMG died with an uncaught exception

### ISSUE THREAD

**Issue by ramuntcho** [MagerValp/AutoDMG#209]
![autodmg](https://user-images.githubusercontent.com/2462665/38196654-8ce4d05a-3684-11e8-8142-1b57c5efd1ad.png)
[AutoDMG 2018-04-02 13.24.log](https://github.com/MagerValp/AutoDMG/files/1868080/AutoDMG.2018-04-02.13.24.log)

## Description of issue

 I have used AutoDMG on the same Mac 2 weeks ago. But now, when I try to open AutoDMG, I have this window which appears and I must quit.

## Expected behavior

Normal behavior

## Actual behavior

AutoDMG doesn't open.

## Steps to reproduce

1. Double-clic AutoDMG
2. It doesn't launch, just an error window appears

## Log file

_(Save the debug log and attach it by dragging it here)_

**Comment by TinyAtJamf** [comment]
Also seeing the same. Was working in 10.13.4 Beta 4 or 5 I think. Upgraded to 10.13.4 Release this morning and hit it every time. Log attached.

[AutoDMG 2018-04-02 08.19.log](https://github.com/MagerValp/AutoDMG/files/1868152/AutoDMG.2018-04-02.08.19.log)

**Comment by apizz** [comment]
I can confirm the same as well.  Only difference was machine running 10.13.3 previously without issue and upgrading to 10.13.4 producing the error.

**Comment by l3ftb3hind** [comment]
also seeing this on 10.12.6, old version of autoDMG as well as the current is throwing the same error

**Comment by mikecarver** [comment]
I am seeing this on 10.13.3 as well

**Comment by l3ftb3hind** [comment]
just tried it on a clean 10.12.6 install and it opens fine, i am assuming an update borked python?

**Comment by MagerValp** [comment]
Sorry folk, I pushed a bad update. It’s fixed now, but if AutoDMG crashes on startup before it can update, delete `~/Library/Application Support/AutoDMG/UpdateProfiles.plist`.

**Comment by l3ftb3hind** [comment]
Hmmm, still crashing for me, I did delete that plist as well, any other advice?

**Comment by l3ftb3hind** [comment]
Ok, I did get it to work, thanks so much!!!

**Comment by cattleman1** [comment]
Thank you for the fix, building my base now!!

**Comment by MagerValp** [comment]
This is fixed in 1.8.1.
